// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsAyIqtDcGG-Vov5UYGU0xncflz2yM_4k',
    appId: '1:318041255310:web:accc06dfa2a6cc648288df',
    messagingSenderId: '318041255310',
    projectId: 'ijob-clone-app-843b9',
    authDomain: 'ijob-clone-app-843b9.firebaseapp.com',
    storageBucket: 'ijob-clone-app-843b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO3DZ4-TA3Cxk-ZurQDdm9dOH48swZlH8',
    appId: '1:318041255310:android:420a283e61a7eda38288df',
    messagingSenderId: '318041255310',
    projectId: 'ijob-clone-app-843b9',
    storageBucket: 'ijob-clone-app-843b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7y2oj1a3L7HrB1Bw44fZhtuOWQ9SZkLA',
    appId: '1:318041255310:ios:29d045b7026c41868288df',
    messagingSenderId: '318041255310',
    projectId: 'ijob-clone-app-843b9',
    storageBucket: 'ijob-clone-app-843b9.firebasestorage.app',
    iosBundleId: 'com.example.ijobCloneApp',
  );
}
